remote_theme: pmarsceill/just-the-docs
title: "Nights Software Documentation"
description: "A comprehensive documentation explaining the installation process of FiveM resources sold by Nights Software."
baseurl: "/"
url: "https://docs.nights-software.com"

permalink: pretty
exclude: ["LICENSE.txt", "README.md"]

heading_anchors: true

# Enhanced navigation and search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/\-]+/

# Better navigation structure
nav_external_links: true
nav_external_links_new_tab: true

# Improved aux links
aux_links:
  "Nights Software Webstore":
    - "//store.nights-software.com/"
  "Discord Community":
    - "//discord.nights-software.com/"
  "YouTube Channel":
    - "//www.youtube.com/channel/UC7DWPjF5daoykiD-q6SvYRA"
aux_links_new_tab: true

# Enhanced UI features
back_to_top: true
back_to_top_text: "Back to top"

# Footer improvements
footer_content: "Copyright &copy; 2025 Nights Software | Built with [Just the Docs](https://just-the-docs.github.io/just-the-docs/)"

# Last edit tracking
last_edit_timestamp: true
last_edit_time_format: "%B %e, %Y at %I:%M %p"

# Color scheme and styling
color_scheme: light
dark_mode_toggle: true

# Callouts and alerts
callouts_level: 1
callouts:
  warning:
    name: Warning
    color: yellow
  note:
    name: Note
    color: blue
  tip:
    name: Tip
    color: green
  important:
    name: Important
    color: red

# Mermaid diagrams support
mermaid:
  theme:
    light: default
    dark: dark

# Math support
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false