remote_theme: pmarsceill/just-the-docs
title: "Nights Software Documentation"
description: "A documentation explaining the installation process of FiveM resources sold by Nights Software."
baseurl: "/"
url: "https://docs.nights-software.com"

permalink: pretty
exclude: ["LICENSE.txt", "README.md"]

heading_anchors: true

aux_links:
  "Nights Software Webstore":
    - "//store.nights-software.com/"
aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2025 Nights Software"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
